export const resourcesDetails = {
  hivAidsresources: {
    r1name: "AIDS Care Ocean State (ACOS)",
    r1number: "(401) 781-0665",
    r1location: "Providence",
    r2name: "Crossroads RI",
    r2number: "(401) 521-2255",
    r2location: "Providence",
    r3name: "Cranston Community Action Partnership (CCAP)",
    r3number: "(401) 943-1981",
    r3location: "Cranston",
    r4name: "Northwest Community Health Services",
    r4number: "(401) 568-7661",
    r4location: "Pascoag",
    r5name: "RI HIV/AIDS Hotline",
    r5number: "(800) 726-3010",
    r6name: "Progreso Latino",
    r6number: "(401) 728-5920",
    r6location: "Central Falls",
    r7name: "Thundermist Health Center of South County",
    r7number: "(401) 783-0523",
    r7location: "Wakefield",
    r8name: "Visiting Nurse Home & Hospice",
    r8number: "(401) 849-2101",
    r8location: "Newport",
    r9name: "Youth Pride",
    r9number: "(401) 421-5626",
  },
  dayOne: {
    r1name: "Day One",
    r1website: "https://www.dayoneri.org/",
    r1number: "1 800 494 8100",
  },
  sojournerHouse: {
    r1name: "Sojourner House",
    r1website: "http://www.sojournerri.org/",
    r1number: "401-765-3232",
  },
  elizabaethBuffamChase: {
    r1name: "Elizabeth Buffam Chase",
    r1website: "https://www.ebccenter.org/residential-services",
    r1number: "Hotline: (401)738-1700",
  },
  riChildrenAdvocacyCenter: {
    r1name: "RI Children Advocacy Center",
    r1website: "https://www.dayoneri.org/childrens-advocacy-center",
    r1number: "401-421-4100 119",
  },
  nationalDomesticViolenceHotline: {
    r1name: "National Domestic Violence Hotline",
    r1website: "https://www.thehotline.org/",
    r1number: "800–799–7233",
  },
  nationalResourceCenterOnDomesticViolence: {
    r1name: "National Resource Center On Domestic Violence",
    r1website: "http://www.nrcdv.org/",
    r1number: "(800) 799-7233",
  },
  officeForVictimsOfCrime: {
    r1name: "Office For Victims Of Crime",
    r1website: "https://www.ovc.gov/",
    r1number: "(800) 363-0441",
  },
  leaAndCourtAdvocateInfo: {},
  vineCrimeVictimAdvocate: {},
  dcyf: {},
  nationalCenterForVictimsOfCrime: {},
  riCvcp: {},
  bradleyHospitalAndTidesFamilyService: {},
  familyServicesOfRiAndFamilyCommunityCarePartnership: {},
  dvPartnersUnderRICADVAndCounselingResources: {},
  TRO: {},
  undocumentedInfo: {},
  trafickingSurvivorResources: {},
  legalCounselingRestitutionLink: {},
  legalAssistanceResources: {},
  victimbarLink: {},
  volunteerLawyerProgram: {},
  homelessnessResources: {},
  helplineRI: {},
  CAP: {},
  DHS: {},
  GLBTQDomesticViolenceProject: {},
  GLAD: {},
  youthPrideInc: {},
  relay: {},
  NSPL: {},
};
